apiVersion: v1
kind: ServiceAccount
metadata:
  name: marblerun-coordinator
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.global.coordinatorComponentLabel }}: controller
    {{ .Values.global.coordinatorNamespaceLabel }}: {{ .Release.Namespace }}
{{- if .Values.global.pullSecret }}
imagePullSecrets:
  - name: {{ .Values.global.pullSecret }}
{{- end }}
