apiVersion: v1
kind: ServiceAccount
metadata:
  name: edg-mesh-coordinator
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ .Values.global.coordinatorComponentLabel }}: controller
    {{ .Values.global.coordinatorNamespaceLabel }}: {{ .Values.global.namespace }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
