# Default values for edg-mesh-coordinator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# Values that are passed along to sub-charts
global:
  imagePullPolicy:  IfNotPresent

  namespace: edg-mesh

  # Additional annotations to add to all pods
  podAnnotations: {}

  # Additional labels to add to all pods
  podLabels: {}

  # control plane labels
  coordinatorComponentLabel: edgeless.systems/control-plane-component
  coordinatorNamespaceLabel: edgeless.systems/control-plane-ns

  # For Private docker registries, authentication is needed.
  #  Registry secrets are applied to the respective service accounts
  # pullSecret:
  # pullSecret: my-private-docker-registry-login-secret




# coordinator configuration
coordinator:
  coordinatorImage: ghcr.io/edgelesssys/coordinator
  coordinatorImageVersion: v0.1.0
  coordinatorReplicas: 1

  # Environment configuration for the coordinator control-plane
  # EDG_COORDINATOR_MESH needs to be configured to the same port in the data-plane 
  EDG_COORDINATOR_MESH_HOST: "0.0.0.0"
  EDG_COORDINATOR_MESH_PORT: 25554
  # EDG_COORDINATOR_CLIENT needs to be configured to the same port your client tool stack 
  EDG_COORDINATOR_CLIENT_HOST: "0.0.0.0"
  EDG_COORDINATOR_CLIENT_PORT: 25555
  # DNS_NAMES need need to be set according to service names
  EDG_COORDINATOR_DNS_NAMES: "coordinator-mesh-api,coordinator-client-api,coordinator-mesh-api.emojivoto,coordinator-client-api.emojivoto,coordinator-mesh-api.emojivoto.svc.cluster.local,coordinator-client-api.emojivoto.svc.cluster.local"
  # SEAL_DIR needs to be set according to persistent storage
  EDG_COORDINATOR_SEAL_DIR: "/coordinator/data/"
  # OE_SIMULATION needs be set to "1" when running on systems without SGX1+FLC capabilities
  OE_SIMULATION: "0"

  resources:
    limits:
      # Disable this if your running on a cluster with an SGX Device Plugin
      kubernetes.azure.com/sgx_epc_mem_in_MiB: 10

  # Set the storage class for your cluster  
  # storageClass:


# Tolerations constraints for control-plane components
# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations:
- key: kubernetes.azure.com/sgx_epc_mem_in_MiB

# Node selection constraints for control-plane components
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector.
nodeSelector:
  beta.kubernetes.io/os: linux
